# Konfiguration för hybridkategorisering
# Kombinerar regelbaserad och AI-baserad kategorisering
config:
  # Regelbaserad kategorisering körs först
  use_rules: true
  
  # AI-fallback aktiveras vid låg säkerhet eller okänd kategori
  use_ai_fallback: true
  
  # Tröskelvärde för säkerhet (0.0-1.0)
  # Under detta värde flaggas transaktionen för manuell granskning
  confidence_threshold: 0.7
  
  # Flagga transaktioner för manuell granskning om säkerheten är låg
  flag_low_confidence: true
  
  # Minsta tröskelvärde för AI-kategorisering
  # Under detta används "Okategoriserad"
  ai_min_confidence: 0.5

categories:
  mat:
    keywords:
      - ica
      - coop
      - willys
      - hemköp
      - lidl
      - max
      - burger
      - restaurant
      - pizzeria
    # Hög säkerhet vid exakt matchning
    confidence: 0.95

  boende:
    keywords:
      - hyra
      - elräkning
      - el-räkning
      - vatten
      - bredband
      - internet
      - försäkring bostads
    confidence: 0.95

  transport:
    keywords:
      - bensin
      - diesel
      - circle k
      - shell
      - ingo
      - ok/q8
      - preem
      - sl
      - uber
      - taxi
      - parkering
    confidence: 0.95

  nöje:
    keywords:
      - spotify
      - netflix
      - hbo
      - viaplay
      - disney
      - bio
      - konsert
      - teater
      - streaming
    confidence: 0.95

  kläder:
    keywords:
      - h&m
      - hm
      - zara
      - kappahl
      - dressman
      - lindex
      - stadium
    confidence: 0.95

  hälsa:
    keywords:
      - apoteket
      - apotek
      - läkare
      - tandläkare
      - vårdcentral
      - sjukhus
      - optiker
    confidence: 0.95

  försäkring:
    keywords:
      - försäkring
      - if försäkring
      - folksam
      - länsförsäkringar
      - trygg hansa
    confidence: 0.95

  inkomst:
    keywords:
      - lön
      - salary
      - utbetalning
    confidence: 0.95
