income_tracker:
  incomes:
    - amount: 28000.0
      category: null
      date: '2025-11-25'
      frequency: monthly
      person: Robin
      recurring: true
      source: Lön
    - amount: 28000.0
      category: null
      date: '2025-12-25'
      frequency: monthly
      person: Robin
      recurring: true
      source: Lön
    - amount: 25000.0
      category: null
      date: '2025-12-25'
      frequency: monthly
      person: Partner
      recurring: true
      source: Lön
    - amount: 28000.0
      category: null
      date: '2025-12-25'
      frequency: monthly
      person: Robin
      recurring: true
      source: Lön
    - amount: 25000.0
      category: null
      date: '2025-12-25'
      frequency: monthly
      person: Partner
      recurring: true
      source: Lön
  people:
    - name: Robin
      one_time_income:
        - amount: 5000
          date: '2025-12-10'
          source: Frilans
      recurring_income:
        - amount: 28000
          frequency: monthly
          source: Lön
    - name: Partner
      recurring_income:
        - amount: 22000
          frequency: monthly
          source: Lön
