upcoming_bills:
  bills:
  - amount: 900
    category: Boende
    due_date: '2025-11-30'
    name: Elräkning
  - amount: 399
    category: Boende
    due_date: '2025-11-15'
    name: Internet
  - amount: 109
    category: Nöje
    due_date: '2025-11-20'
    name: Spotify
  - amount: 900.0
    category: Boende
    due_date: '2025-11-30'
    frequency: monthly
    name: Test Elräkning
    paid: false
    recurring: true
  - amount: 399.0
    category: Boende
    due_date: '2025-12-15'
    frequency: monthly
    name: Internet
    paid: false
    recurring: true
  - amount: 450.0
    category: Försäkring
    due_date: '2025-12-20'
    frequency: monthly
    name: Försäkring
    paid: false
    recurring: true
  - amount: 399.0
    category: Boende
    due_date: '2025-12-15'
    frequency: monthly
    name: Internet
    paid: false
    recurring: true
  - amount: 450.0
    category: Försäkring
    due_date: '2025-12-20'
    frequency: monthly
    name: Försäkring
    paid: false
    recurring: true
